name: Node.js Express with helmet
version: 0.2.10
description: Express web framework for Node.js with helmet
license: Apache-2.0
language: nodejs
maintainers:
  - name: Chris Bailey
    email: cnbailey@gmail.com
    github-id: seabaylea
  - name: Neeraj Laad
    email: neeraj.laad@gmail.com
    github-id: neeraj-laad
default-template: simple
